CREATE OR REPLACE VIEW SEAT_AVAILABILITY AS
SELECT V.VENUE_ID, V.VENUE_NAME, 
       V.VENUE_CAPACITY - NVL(SUM(R.QUANTITY), 0) AS SEATS_AVAILABLE
FROM VENUE V
LEFT JOIN EVENT_SCHEDULE ES ON V.VENUE_ID = ES.VENUE_VENUE_ID
LEFT JOIN REGISTRATION R ON ES.EVENT_EVENT_ID = R.EVENT_EVENT_ID
GROUP BY V.VENUE_ID, V.VENUE_NAME, V.VENUE_CAPACITY;


CREATE OR REPLACE VIEW EVENT_TICKET_SALES AS
SELECT E.EVENT_ID, E.EVENT_NAME, 
       NVL(SUM(R.TICKET_PRICE * R.QUANTITY), 0) AS TOTAL_TICKET_SALES
FROM EVENT E
LEFT JOIN REGISTRATION R ON E.EVENT_ID = R.EVENT_EVENT_ID
GROUP BY E.EVENT_ID, E.EVENT_NAME;


CREATE OR REPLACE VIEW ORGANIZER_REVENUE AS
SELECT O.ORGANIZER_ID, O.COMPANY_NAME, 
       NVL(SUM(S.AMOUNT_SPONSORED), 0) AS TOTAL_SPONSORSHIP,
       NVL(SUM(R.TICKET_PRICE * R.QUANTITY), 0) AS TOTAL_TICKET_SALES,
       NVL(SUM(S.AMOUNT_SPONSORED), 0) + NVL(SUM(R.TICKET_PRICE * R.QUANTITY), 0) AS TOTAL_REVENUE
FROM ORGANIZER O
LEFT JOIN EVENT E ON O.ORGANIZER_ID = E.ORGANIZER_ORGANIZER_ID
LEFT JOIN SPONSOR S ON E.EVENT_ID = S.EVENT_EVENT_ID
LEFT JOIN REGISTRATION R ON E.EVENT_ID = R.EVENT_EVENT_ID
GROUP BY O.ORGANIZER_ID, O.COMPANY_NAME;



