SELECT ORGANIZER_ID,COMPANY_NAME,
    SUM(PROFIT_LOSS) AS "PROFIT/LOSS", 
    SUM(TICKET_REVENUE) AS "REVENUE_TICKETS", 
    AVG(TICKET_REVENUE_PERCENTAGE) AS "REVENUE_TICKETS_PERCENTAGE",
    SUM(SPONSORSHIP_REVENUE) AS "REVENUE_SPONSORS", 
    AVG(SPONSORSHIP_REVENUE_PERCENTAGE) AS "REVENUE_SPONSORS_PERCENTAGE", 
    AVG(CAPACITY_UTILIZATION_PERCENTAGE) AS "VENUE_UTILIZATION",
    SUM(PLANNED_COST) AS "ESTIMATED_COSTS"
FROM REPORT_EVENT_PROFIT_LOSS 
GROUP BY ORGANIZER_ID,COMPANY_NAME
ORDER BY ORGANIZER_ID;