SET SERVEROUTPUT ON;
BEGIN
    FOR c IN (SELECT USERNAME FROM DBA_USERS 
    WHERE USERNAME IN ('EVENT_ADMIN', 'EVENT_ORGANIZER', 'EVENT_SPONSOR', 'EVENT_ATTENDEE', 'EVENT_VIEWER', 'VENUE_MANAGER')) 
    LOOP
        EXECUTE IMMEDIATE 'DROP USER ' || c.USERNAME || ' CASCADE';
        DBMS_OUTPUT.PUT_LINE('USER DROPPED: ' || c.USERNAME );
    END LOOP;
END;
/

COMMIT;

-- Create Users
CREATE USER EVENT_ADMIN IDENTIFIED BY Admin_123456;
CREATE USER EVENT_ORGANIZER IDENTIFIED BY Organizer_123456;
CREATE USER EVENT_SPONSOR IDENTIFIED BY Sponsor_123456;
CREATE USER EVENT_ATTENDEE IDENTIFIED BY Attendee_123456;
CREATE USER EVENT_VIEWER IDENTIFIED BY Viewer_123456;
CREATE USER VENUE_MANAGER IDENTIFIED BY VenueMgr_123456;

-- COMMIT Changes to Database
COMMIT;
