SET SERVEROUTPUT ON;
BEGIN
    FOR c IN (SELECT USERNAME FROM DBA_USERS 
    WHERE USERNAME IN ('EVENT_ADMIN', 'EVENT_ORGANIZER', 'EVENT_SPONSOR', 'EVENT_ATTENDEE', 'EVENT_VIEWER', 'VENUE_MANAGER')) 
    LOOP
        EXECUTE IMMEDIATE 'DROP USER ' || c.USERNAME || ' CASCADE';
        DBMS_OUTPUT.PUT_LINE('USER DROPPED: ' || c.USERNAME );
    END LOOP;
END;
/

COMMIT;

-- Create Users
CREATE USER EVENT_ADMIN IDENTIFIED BY Admin_123456;
CREATE USER EVENT_ORGANIZER IDENTIFIED BY Organizer_123456;
CREATE USER EVENT_SPONSOR IDENTIFIED BY Sponsor_123456;
CREATE USER EVENT_ATTENDEE IDENTIFIED BY Attendee_123456;
CREATE USER EVENT_VIEWER IDENTIFIED BY Viewer_123456;
CREATE USER VENUE_MANAGER IDENTIFIED BY VenueMgr_123456;

-- Admin with all privileges
GRANT CONNECT, RESOURCE TO EVENT_ADMIN; -- Basic roles for database access
ALTER USER EVENT_ADMIN DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT UNLIMITED TABLESPACE TO EVENT_ADMIN; -- Administrative privilege for unlimited storage
GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO EVENT_ADMIN;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO EVENT_ADMIN;

-- Grant basic privileges to other users
GRANT CONNECT, RESOURCE TO EVENT_ORGANIZER;
GRANT CONNECT, RESOURCE TO EVENT_SPONSOR;
GRANT CONNECT, RESOURCE TO EVENT_ATTENDEE;
GRANT CONNECT, RESOURCE TO EVENT_VIEWER;
GRANT CONNECT, RESOURCE TO VENUE_MANAGER;

-- COMMIT Changes to Database
COMMIT;

-- Output confirmation message
BEGIN
    DBMS_OUTPUT.PUT_LINE('Users created and privileges granted successfully.');
END;
/

